@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

package ModelManager {
    class AB as "<u>addressBook\n:AddressBook</u>"
    class Prev as "previousAddressBook\n= null" #DDDDDD
    class Redo as "redoAddressBook\n= null" #DDDDDD
}

AB -[hidden]right-> Prev
Prev -[hidden]right-> Redo

note bottom of AB : Current address book
@end
