@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":ModelManager" as ModelManager MODEL_COLOR
participant "currentAB\n:AddressBook" as CurrentAB MODEL_COLOR
participant "snapshot\n:AddressBook" as Snapshot MODEL_COLOR
end box

[-> ModelManager : undoAddressBook()
activate ModelManager

ModelManager -> CurrentAB ** : new AddressBook(addressBook)
note right: Save current state\ninto redoAddressBook

ModelManager -> ModelManager : setAddressBook(previousAddressBook)
activate ModelManager
ModelManager -> CurrentAB : resetData(previousAddressBook)
activate CurrentAB
CurrentAB --> ModelManager
deactivate CurrentAB
deactivate ModelManager

ModelManager -> ModelManager : previousAddressBook = null

[<-- ModelManager
deactivate ModelManager

@enduml
