@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "delete 5"

package ModelManager {
    class AB as "<u>addressBook\n:AddressBook</u>" #FFFFAA
    class Prev as "<u>previousAddressBook\n:AddressBook</u>" #AAFFAA
    class Redo as "redoAddressBook\n= null" #DDDDDD
}

AB -[hidden]right-> Prev
Prev -[hidden]right-> Redo

note bottom of AB : After delete\n(person 5 removed)
note bottom of Prev : Snapshot before delete\n(person 5 still present)
@end
